version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps)

  - package-ecosystem: github-actions
    directory: /pipeline/github/job/upload-sbom-to-dependency-track
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps)
